# permissions for end users to edit nginxops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nginxop-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo-op
    app.kubernetes.io/part-of: demo-op
    app.kubernetes.io/managed-by: kustomize
  name: nginxop-editor-role
rules:
- apiGroups:
  - nginxop.my.domain
  resources:
  - nginxops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nginxop.my.domain
  resources:
  - nginxops/status
  verbs:
  - get
