# permissions for end users to view nginxops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nginxop-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo-op
    app.kubernetes.io/part-of: demo-op
    app.kubernetes.io/managed-by: kustomize
  name: nginxop-viewer-role
rules:
- apiGroups:
  - nginxop.my.domain
  resources:
  - nginxops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nginxop.my.domain
  resources:
  - nginxops/status
  verbs:
  - get
