apiVersion: nginxop.my.domain/v1
kind: NginxOp
metadata:
  labels:
    app.kubernetes.io/name: nginxop
    app.kubernetes.io/instance: nginxop-sample
    app.kubernetes.io/part-of: demo-op
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: demo-op
  name: nginx-op-sample
spec:
  replicas: 1
  host: foo.bar
  image: "nginx:latest"
