name: build, test, create image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        go-version: 1.19

    - name: Lint
      run: make fmt vet

    - name: Build
      run: make fmt build

    - name: Test
      run: make test
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nginxop-controller:$(date +%s)
